// lily-design-system-vue-nuxt-examples/pages/components/[slug].vue
<script setup lang="ts">
import { components } from "~/data/components";
import { componentDemos } from "~/data/component-demos";
import { componentExamples } from "~/data/component-examples";

const route = useRoute();
const slug = route.params.slug as string;
const component = components.find(c => c.slug === slug);

if (!component) {
    throw createError({ statusCode: 404, statusMessage: "Component not found" });
}

const demoHtml = componentDemos[slug];
const example = componentExamples[slug];
</script>

<template>
    <main class="page-wrapper">
        <p><NuxtLink to="/components">&larr; Back to components</NuxtLink></p>
        <h1>{{ component!.name }}</h1>
        <p>{{ component!.description }}</p>

        <h2>Demo</h2>
        <div class="card" style="padding: 1.5rem;">
            <div v-if="demoHtml" v-html="demoHtml"></div>
            <p v-else><em>No demo available.</em></p>
        </div>

        <details v-if="demoHtml">
            <summary>Show demo markup</summary>
            <pre tabindex="0"><code>{{ demoHtml }}</code></pre>
        </details>

        <template v-if="example?.variants?.length">
            <h2>More examples</h2>
            <div v-for="variant in example.variants" :key="variant.title">
                <h3>{{ variant.title }}</h3>
                <div class="card" style="padding: 1.5rem;" v-html="variant.html"></div>
                <details>
                    <summary>Show markup</summary>
                    <pre tabindex="0"><code>{{ variant.html }}</code></pre>
                </details>
            </div>
        </template>

        <h2>Details</h2>
        <dl>
            <dt>Name</dt>
            <dd>{{ component!.name }}</dd>
            <dt>Slug</dt>
            <dd><code>{{ component!.slug }}</code></dd>
            <dt>Description</dt>
            <dd>{{ component!.description }}</dd>
        </dl>
        <h2>Usage</h2>
        <pre tabindex="0"><code v-if="example?.usage">{{ example.usage.code }}</code><code v-else>&lt;{{ component!.name }} /&gt;</code></pre>
        <h2>Import</h2>
        <pre tabindex="0"><code>import {{ component!.name }} from "~/components/{{ component!.name }}.vue";</code></pre>
    </main>
</template>

// lily-design-system-react-next-examples/app/components/[slug]/page.tsx
import Link from "next/link";
import { components } from "@/app/data/components";
import { componentDemos } from "@/app/data/component-demos";
import { componentExamples } from "@/app/data/component-examples";
import { notFound } from "next/navigation";

interface Props {
    params: Promise<{ slug: string }>;
}

export default async function ComponentDetailPage({ params }: Props) {
    const { slug } = await params;
    const component = components.find((c) => c.slug === slug);
    if (!component) notFound();

    const demoHtml = componentDemos[slug];
    const example = componentExamples[slug];

    return (
        <main className="page-wrapper">
            <p><Link href="/components">&larr; Back to components</Link></p>
            <h1>{component.name}</h1>
            <p>{component.description}</p>

            <h2>Demo</h2>
            <div className="card" style={{ padding: "1.5rem" }}>
                {demoHtml ? (
                    <div dangerouslySetInnerHTML={{ __html: demoHtml }} />
                ) : (
                    <p><em>No demo available.</em></p>
                )}
            </div>

            {demoHtml && (
                <details>
                    <summary>Show demo markup</summary>
                    <pre tabIndex={0}><code>{demoHtml}</code></pre>
                </details>
            )}

            {example?.variants?.length ? (
                <>
                    <h2>More examples</h2>
                    {example.variants.map((variant) => (
                        <div key={variant.title}>
                            <h3>{variant.title}</h3>
                            <div className="card" style={{ padding: "1.5rem" }}>
                                <div dangerouslySetInnerHTML={{ __html: variant.html }} />
                            </div>
                            <details>
                                <summary>Show markup</summary>
                                <pre tabIndex={0}><code>{variant.html}</code></pre>
                            </details>
                        </div>
                    ))}
                </>
            ) : null}

            <h2>Details</h2>
            <dl>
                <dt>Name</dt>
                <dd>{component.name}</dd>
                <dt>Slug</dt>
                <dd><code>{component.slug}</code></dd>
                <dt>Description</dt>
                <dd>{component.description}</dd>
            </dl>
            <h2>Usage</h2>
            <pre tabIndex={0}><code>{example?.usage ? example.usage.code : `<${component.name} />`}</code></pre>
            <h2>Import</h2>
            <pre tabIndex={0}><code>{`import ${component.name} from "@lily/${component.name}";`}</code></pre>
        </main>
    );
}

export function generateStaticParams() {
    return components.map((c) => ({ slug: c.slug }));
}
