// lily-design-system-angular-helpers/lily-design-system-angular-link-picker/examples/basic.component.ts
import { Component } from "@angular/core";
import { LinkPicker, type LinkItem } from "../link-picker.component";

// The app defines the links: the package ships no routes and no English.
@Component({
  selector: "example-basic",
  standalone: true,
  imports: [LinkPicker],
  template: `<lily-link-picker label="Pages" [links]="links" />`,
})
export class Basic {
  links: LinkItem[] = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about/" },
  { label: "Contact Us", href: "/contact/" },
  { label: "Privacy Policy", href: "/privacy/" },
];
}

// lily-design-system-react-helpers/lily-design-system-react-link-picker/examples/Basic.tsx
import LinkPicker, { type LinkItem } from "../LinkPicker";

// The app defines the links: the package ships no routes and no English.
const links: LinkItem[] = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about/" },
  { label: "Contact Us", href: "/contact/" },
  { label: "Privacy Policy", href: "/privacy/" },
];

export default function Basic() {
  return <LinkPicker label="Pages" links={links} />;
}
