// lily-design-system-vue-helpers/lily-design-system-vue-picker-bar/PickerBar.vue
<script lang="ts">
import ThemePicker from "@lilydesignsystem/vue-theme-picker";
import LocalePicker from "@lilydesignsystem/vue-locale-picker";
import TextSizePicker from "@lilydesignsystem/vue-text-size-picker";
import SharePicker from "@lilydesignsystem/vue-share-picker";
import LinkPicker from "@lilydesignsystem/vue-link-picker";
import SearchPicker from "@lilydesignsystem/vue-search-picker";
import type { Props as ThemePickerProps } from "@lilydesignsystem/vue-theme-picker";
import type { Props as LocalePickerProps } from "@lilydesignsystem/vue-locale-picker";
import type { Props as TextSizePickerProps } from "@lilydesignsystem/vue-text-size-picker";
import type {
    Props as SharePickerProps,
    ShareTarget,
} from "@lilydesignsystem/vue-share-picker";
import type { Props as SearchPickerProps } from "@lilydesignsystem/vue-search-picker";
import type {
    Props as LinkPickerProps,
    LinkItem,
} from "@lilydesignsystem/vue-link-picker";

/**
 * All 45 Lily reference theme slugs (see `themes/` at the repo root),
 * sorted alphabetically except the United Kingdom and United States
 * government/public-sector themes, which sort last as one alphabetical
 * group of their own. Mirrors `theme-picker`'s own title-casing of each
 * slug, so no `themeLabels` override is needed for these to read well.
 */
export const DEFAULT_THEMES: string[] = [
    "abyss",
    "acid",
    "adobe-spectrum",
    "aqua",
    "autumn",
    "black",
    "bumblebee",
    "business",
    "caramellatte",
    "cmyk",
    "coffee",
    "corporate",
    "cupcake",
    "cyberpunk",
    "dark",
    "dim",
    "dracula",
    "emerald",
    "fantasy",
    "forest",
    "garden",
    "halloween",
    "lemonade",
    "light",
    "lofi",
    "luxury",
    "mozilla-protocol",
    "night",
    "nord",
    "pastel",
    "retro",
    "silk",
    "sunset",
    "synthwave",
    "valentine",
    "winter",
    "wireframe",
    "united-kingdom-government-digital-service",
    "united-kingdom-national-health-service-england-for-patients",
    "united-kingdom-national-health-service-england-for-practitioners",
    "united-kingdom-national-health-service-scotland-for-patients",
    "united-kingdom-national-health-service-scotland-for-practitioners",
    "united-kingdom-national-health-service-wales-for-patients",
    "united-kingdom-national-health-service-wales-for-practitioners",
    "united-states-web-design-system",
];

/**
 * The seven-step text-size scale. Each slug title-cases to exactly the
 * requested label ("largest" → "Largest", …) via `text-size-picker`'s
 * own default `labelFor`, so no `sizeLabels` override is needed either.
 */
export const DEFAULT_SIZES: string[] = [
    "largest",
    "larger",
    "large",
    "normal",
    "small",
    "smaller",
    "smallest",
];

/** Accessible names for the pickers. Required — no English default (`link` only when `links` is given). */
export type PickerBarLabels = {
    /**
     * Accessible name for the link picker's button and list. Needed only when `links` is
     * supplied; the link picker renders only when both are present.
     */
    link?: string;
    /** Accessible name for the search picker's button and search landmark. */
    search: string;
    /** Accessible name for the search picker's text field. */
    searchInput: string;
    /** Accessible name for the search picker's ⏎ submit button. */
    searchSubmit: string;
    /** Accessible name for the theme picker's button and listbox. */
    theme: string;
    /** Accessible name for the locale picker's button and listbox. */
    locale: string;
    /** Accessible name for the text-size picker's button and listbox. */
    textSize: string;
    /** Accessible name for the share picker's button and list. */
    share: string;
};

/** Public props for PickerBar. See `spec/index.md` §4 for the contract. */
export type Props = {
    /** Accessible names for each picker. */
    labels: PickerBarLabels;

    /** Page links for the link picker (a home icon), which renders FIRST — leftmost. Omitted or empty: no link picker. */
    links?: LinkItem[];
    /** Extra LinkPicker props (e.g. `navigate`), bound after this bar's own. */
    linkProps?: Partial<Omit<LinkPickerProps, "label" | "links" | "class">>;

    /** Extra SearchPicker props (e.g. `action`, `navigate`, `placeholder`), bound after this bar's own. */
    searchProps?: Partial<
        Omit<SearchPickerProps, "label" | "inputLabel" | "submitLabel" | "class">
    >;

    /** Base URL of the themes directory, forwarded to ThemePicker. */
    themesUrl: string;
    /** Available theme slugs. Defaults to {@link DEFAULT_THEMES}. */
    themes?: string[];
    /** Extra ThemePicker props, bound after this bar's own (v-bind="themeProps"). */
    themeProps?: Partial<
        Omit<ThemePickerProps, "label" | "themesUrl" | "themes" | "class">
    >;

    /** Available locale codes. No catalog default exists — supply the set you support. */
    locales: string[];
    /** Extra LocalePicker props, bound after this bar's own. */
    localeProps?: Partial<Omit<LocalePickerProps, "label" | "locales" | "class">>;

    /** Available size slugs. Defaults to {@link DEFAULT_SIZES}. */
    sizes?: string[];
    /** Extra TextSizePicker props, bound after this bar's own. */
    textSizeProps?: Partial<
        Omit<TextSizePickerProps, "label" | "sizes" | "class">
    >;

    /** Destinations offered by the share picker. Empty is valid if `shareProps.copyLabel` is set. */
    shareTargets?: ShareTarget[];
    /** Extra SharePicker props, bound after this bar's own. */
    shareProps?: Partial<Omit<SharePickerProps, "label" | "targets" | "class">>;

    /** Extra CSS class on the root element. */
    class?: string;
};
</script>

<script setup lang="ts">
const props = withDefaults(defineProps<Props>(), {
    links: () => [],
    linkProps: () => ({}),
    searchProps: () => ({}),
    themes: () => DEFAULT_THEMES,
    themeProps: () => ({}),
    localeProps: () => ({}),
    sizes: () => DEFAULT_SIZES,
    textSizeProps: () => ({}),
    shareTargets: () => [],
    shareProps: () => ({}),
    class: "",
});

// Vue separates props from events by design, so — unlike the Svelte
// canonical's `onChange` prop inside each `*Props` bag — the Vue port
// re-emits each wrapped picker's own event under a bar-scoped name,
// fully typed, rather than accepting an untyped `onChange` key inside
// `themeProps` et al.
const emit = defineEmits<{
    (event: "link-navigate", id: string, href: string): void;
    (event: "search", query: string, href: string): void;
    (event: "theme-change", value: string): void;
    (event: "locale-change", value: string): void;
    (event: "text-size-change", value: string): void;
    (event: "share", targetId: string, url: string): void;
    (event: "copy", url: string): void;
    (event: "native-share", url: string): void;
}>();
</script>

<template>
    <div :class="`picker-bar ${props.class}`.trim()">
        <LinkPicker
            v-if="links.length > 0 && labels.link"
            :label="labels.link"
            :links="links"
            v-bind="linkProps"
            @navigate="(id: string, href: string) => emit('link-navigate', id, href)"
        />
        <SearchPicker
            :label="labels.search"
            :inputLabel="labels.searchInput"
            :submitLabel="labels.searchSubmit"
            v-bind="searchProps"
            @search="(query: string, href: string) => emit('search', query, href)"
        />
        <ThemePicker
            :label="labels.theme"
            :themesUrl="themesUrl"
            :themes="themes"
            v-bind="themeProps"
            @change="(value: string) => emit('theme-change', value)"
        />
        <LocalePicker
            :label="labels.locale"
            :locales="locales"
            v-bind="localeProps"
            @change="(value: string) => emit('locale-change', value)"
        />
        <TextSizePicker
            :label="labels.textSize"
            :sizes="sizes"
            defaultValue="normal"
            v-bind="textSizeProps"
            @change="(value: string) => emit('text-size-change', value)"
        />
        <SharePicker
            :label="labels.share"
            :targets="shareTargets"
            v-bind="shareProps"
            @share="(targetId: string, url: string) => emit('share', targetId, url)"
            @copy="(url: string) => emit('copy', url)"
            @nativeShare="(url: string) => emit('native-share', url)"
        />
    </div>
</template>

// lily-design-system-react-helpers/lily-design-system-react-picker-bar/PickerBar.tsx
import * as React from "react";

import ThemePicker, {
  type Props as ThemePickerProps,
} from "@lilydesignsystem/react-theme-picker";
import LocalePicker, {
  type Props as LocalePickerProps,
} from "@lilydesignsystem/react-locale-picker";
import TextSizePicker, {
  type Props as TextSizePickerProps,
} from "@lilydesignsystem/react-text-size-picker";
import SharePicker, {
  type Props as SharePickerProps,
  type ShareTarget,
} from "@lilydesignsystem/react-share-picker";
import LinkPicker, {
  type Props as LinkPickerProps,
  type LinkItem,
} from "@lilydesignsystem/react-link-picker";
import SearchPicker, {
  type Props as SearchPickerProps,
} from "@lilydesignsystem/react-search-picker";

/**
 * All 45 Lily reference theme slugs (see `themes/` at the repo root),
 * sorted alphabetically except the United Kingdom and United States
 * government/public-sector themes, which sort last as one alphabetical
 * group of their own. Mirrors `theme-picker`'s own title-casing of each
 * slug, so no `themeLabels` override is needed for these to read well.
 */
export const DEFAULT_THEMES: string[] = [
  "abyss",
  "acid",
  "adobe-spectrum",
  "aqua",
  "autumn",
  "black",
  "bumblebee",
  "business",
  "caramellatte",
  "cmyk",
  "coffee",
  "corporate",
  "cupcake",
  "cyberpunk",
  "dark",
  "dim",
  "dracula",
  "emerald",
  "fantasy",
  "forest",
  "garden",
  "halloween",
  "lemonade",
  "light",
  "lofi",
  "luxury",
  "mozilla-protocol",
  "night",
  "nord",
  "pastel",
  "retro",
  "silk",
  "sunset",
  "synthwave",
  "valentine",
  "winter",
  "wireframe",
  "united-kingdom-government-digital-service",
  "united-kingdom-national-health-service-england-for-patients",
  "united-kingdom-national-health-service-england-for-practitioners",
  "united-kingdom-national-health-service-scotland-for-patients",
  "united-kingdom-national-health-service-scotland-for-practitioners",
  "united-kingdom-national-health-service-wales-for-patients",
  "united-kingdom-national-health-service-wales-for-practitioners",
  "united-states-web-design-system",
];

/**
 * The seven-step text-size scale. Each slug title-cases to exactly the
 * requested label ("largest" → "Largest", …) via `text-size-picker`'s
 * own default `labelFor`, so no `sizeLabels` override is needed either.
 */
export const DEFAULT_SIZES: string[] = [
  "largest",
  "larger",
  "large",
  "normal",
  "small",
  "smaller",
  "smallest",
];

/** Accessible names for the five pickers. Required — no English default. */
export type PickerBarLabels = {
  /**
   * Accessible name for the link picker's button and list. Needed only when `links` is
   * supplied; the link picker renders only when both are present.
   */
  link?: string;
  /** Accessible name for the search picker's button and search landmark. */
  search: string;
  /** Accessible name for the search picker's text field. */
  searchInput: string;
  /** Accessible name for the search picker's ⏎ submit button. */
  searchSubmit: string;
  /** Accessible name for the theme picker's button and listbox. */
  theme: string;
  /** Accessible name for the locale picker's button and listbox. */
  locale: string;
  /** Accessible name for the text-size picker's button and listbox. */
  textSize: string;
  /** Accessible name for the share picker's button and list. */
  share: string;
};

/** Public props for PickerBar. See `spec/index.md` §4 for the contract. */
export type Props = Omit<React.HTMLAttributes<HTMLDivElement>, "children"> & {
  /** Accessible names for each picker. */
  labels: PickerBarLabels;

  /** Page links for the link picker (a home icon), which renders FIRST — leftmost. Omitted or empty: no link picker. */
  links?: LinkItem[];
  /** Extra LinkPicker props (e.g. `navigate`, `onNavigate`), spread after this bar's own. */
  linkProps?: Partial<Omit<LinkPickerProps, "label" | "links">>;

  /** Extra SearchPicker props (e.g. `action`, `navigate`, `placeholder`), spread after this bar's own. */
  searchProps?: Partial<Omit<SearchPickerProps, "label" | "inputLabel" | "submitLabel">>;

  /** Base URL of the themes directory, forwarded to ThemePicker. */
  themesUrl: string;
  /** Available theme slugs. Defaults to {@link DEFAULT_THEMES}. */
  themes?: string[];
  /** Extra ThemePicker props, spread after this bar's own. */
  themeProps?: Partial<Omit<ThemePickerProps, "themesUrl" | "themes">>;

  /** Available locale codes. No catalog default exists — supply the set you support. */
  locales: string[];
  /** Extra LocalePicker props, spread after this bar's own. */
  localeProps?: Partial<Omit<LocalePickerProps, "locales">>;

  /** Available size slugs. Defaults to {@link DEFAULT_SIZES}. */
  sizes?: string[];
  /** Extra TextSizePicker props, spread after this bar's own. */
  textSizeProps?: Partial<Omit<TextSizePickerProps, "sizes">>;

  /** Destinations offered by the share picker. Empty is valid if `shareProps.copyLabel` is set. */
  shareTargets?: ShareTarget[];
  /** Extra SharePicker props, spread after this bar's own. */
  shareProps?: Partial<Omit<SharePickerProps, "targets">>;

  /** Extra CSS class on the root. */
  className?: string;
};

export function PickerBar({
  labels,
  links = [],
  linkProps = {},
  searchProps = {},
  themesUrl,
  themes = DEFAULT_THEMES,
  themeProps = {},
  locales,
  localeProps = {},
  sizes = DEFAULT_SIZES,
  textSizeProps = {},
  shareTargets = [],
  shareProps = {},
  className = "",
  ...restProps
}: Props): React.ReactElement {
  return (
    <div className={`picker-bar ${className}`.trim()} {...restProps}>
      {links.length > 0 && labels.link ? (
        <LinkPicker label={labels.link} links={links} {...linkProps} />
      ) : null}
      <SearchPicker
        label={labels.search}
        inputLabel={labels.searchInput}
        submitLabel={labels.searchSubmit}
        {...searchProps}
      />
      <ThemePicker
        label={labels.theme}
        themesUrl={themesUrl}
        themes={themes}
        {...themeProps}
      />
      <LocalePicker label={labels.locale} locales={locales} {...localeProps} />
      <TextSizePicker
        label={labels.textSize}
        sizes={sizes}
        defaultValue="normal"
        {...textSizeProps}
      />
      <SharePicker
        label={labels.share}
        targets={shareTargets}
        {...shareProps}
      />
    </div>
  );
}

export default PickerBar;
