// lily-design-system-vue-headless/components/Comment.vue
<script setup lang="ts">

    // Comment component
    //
    // A comment is anything that expresses an opinion, observation, explanation, etc.
    //
    // Props:
    //   label — string, optional. Accessible label via aria-label.
    //   default slot — component content.
    //
    // Accessibility:
    //   - native <div> semantics
    //   - aria-label exposes a screen-reader name when label is provided
    //
    // Claude rules:
    //   - Headless: no CSS, no styles — consumer provides all styling

    withDefaults(defineProps<{
        /** Optional accessible label set on aria-label. */
        label?: string;
    }>(), {
        label: undefined,
    });

</script>

<template>
    <!-- Comment.vue -->
    <div
        class="comment"
        :aria-label="label"
        v-bind="$attrs"
    >
        <slot />
    </div>
</template>

// lily-design-system-angular-headless/components/Comment.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

/**
 * Comment — a comment is anything that expresses an opinion, observation, explanation, etc.
 *
 * Headless Angular component. Renders the semantic HTML root with the
 * kebab-case class hook `comment` and the consumer-provided `className`.
 * Ships zero CSS; the consumer styles via the class hook.
 */
@Component({
  selector: "lily-comment",
  standalone: true,
  template: `<div class="comment {{ className() }}" [attr.aria-label]="label() || null"><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Comment {
  readonly label = input<string>("");
  readonly className = input<string>("");
}
