// lily-design-system-react-headless/components/EmptyState.tsx
// EmptyState component
//
// A headless container for "nothing here yet" content. Heading, text and
// actions are supplied by the consumer as children; no icon is bundled.
//
// Props:
//   className -- string, optional. CSS class name.
//   label -- string, optional. When given: role="group" + aria-label.
//   children -- ReactNode. Consumer content.
//   ...restProps -- spread onto the root <div>.
//
// Accessibility: not a live region; role="group" only when labelled.

import React from "react";

export interface EmptyStateProps {
    className?: string;
    /** Optional accessible label; adds role="group". */
    label?: string;
    /** Consumer content. */
    children?: React.ReactNode;
    [key: string]: unknown;
}

export default function EmptyState({
    className = "",
    label = undefined,
    children,
    ...restProps
}: EmptyStateProps) {
    return (
        <div
            className={`empty-state ${className}`}
            role={label ? "group" : undefined}
            aria-label={label}
            {...restProps}
        >
            {children}
        </div>
    );
}

// lily-design-system-angular-headless/components/EmptyState.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

/**
 * EmptyState — a placeholder shown when a list, table, or view has nothing to display yet, with room for guidance and an action
 *
 * Headless Angular component. Root `<div class="empty-state">`; when the
 * optional `label` is given it becomes `role="group"` with that aria-label.
 * Children (heading, text, action) are consumer-supplied. Not a live region.
 * Ships zero CSS.
 */
@Component({
  selector: "lily-empty-state",
  standalone: true,
  template: `<div
    class="empty-state {{ className() }}"
    [attr.role]="label() ? 'group' : null"
    [attr.aria-label]="label() || null"
  ><ng-content /></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EmptyState {
  /** Optional accessible name; when set the root is a labelled group. */
  readonly label = input<string>("");
  readonly className = input<string>("");
}
