// lily-design-system-vue-headless/components/ShowMore.vue
<script setup lang="ts">

    // ShowMore component
    //
    // Long content behind a "show more / show less" toggle. The clamp is
    // consumer CSS keyed on data-expanded on .show-more-content (no inline
    // style); the content always stays in the accessibility tree.
    //
    // Props:
    //   moreLabel -- string, required. Button text while collapsed.
    //   lessLabel -- string, required. Button text while expanded.
    //   expanded -- boolean, default false. Bindable via v-model:expanded.
    //   default slot -- the content.
    //   ...attrs -- fall through onto the root <div>.
    //
    // Keyboard: native <button> (Enter / Space).
    // Accessibility: aria-expanded + aria-controls on the button.

    import { useId } from "vue";

    defineProps<{
        /** Button text while collapsed. */
        moreLabel: string;
        /** Button text while expanded. */
        lessLabel: string;
    }>();

    const expanded = defineModel<boolean>("expanded", { default: false });

    const contentId = `show-more-${useId()}`;

</script>

<template>
    <!-- ShowMore.vue -->
    <div class="show-more">
        <div
            class="show-more-content"
            :id="contentId"
            :data-expanded="expanded"
        >
            <slot />
        </div>
        <button
            type="button"
            class="show-more-button"
            :aria-expanded="expanded"
            :aria-controls="contentId"
            @click="expanded = !expanded"
        >
            {{ expanded ? lessLabel : moreLabel }}
        </button>
    </div>
</template>

// lily-design-system-angular-headless/components/ShowMore.ts
import { ChangeDetectionStrategy, Component, input, model } from "@angular/core";

let nextId = 0;

/**
 * ShowMore — a content region clamped to a shorter height with a button that reveals the rest
 *
 * Headless Angular component. Root `<div class="show-more">` holding
 * `.show-more-content` (id, `data-expanded`) and a native
 * `<button class="show-more-button" aria-expanded aria-controls>` whose text is
 * `moreLabel` / `lessLabel` (both required, no English default). `expanded`
 * is a bindable boolean. The clamp is consumer CSS keyed on `data-expanded`;
 * content stays in the accessibility tree. Keyboard: native button. Ships zero CSS.
 */
@Component({
  selector: "lily-show-more",
  standalone: true,
  template: `<div class="show-more {{ className() }}">
    <div class="show-more-content" [id]="contentId" [attr.data-expanded]="expanded()"><ng-content /></div>
    <button
      type="button"
      class="show-more-button"
      [attr.aria-expanded]="expanded()"
      [attr.aria-controls]="contentId"
      (click)="expanded.set(!expanded())"
    >{{ expanded() ? lessLabel() : moreLabel() }}</button>
  </div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowMore {
  /** Button text while collapsed. */
  readonly moreLabel = input.required<string>();
  /** Button text while expanded. */
  readonly lessLabel = input.required<string>();
  readonly className = input<string>("");
  /** Whether the content is expanded. Bindable. */
  readonly expanded = model<boolean>(false);

  protected readonly contentId = `show-more-${nextId++}`;
}
