// lily-design-system-vue-headless/components/Thinking.vue
<script setup lang="ts">

    // Thinking component
    //
    // A native <details> disclosure for an AI "reasoning" block. Closed by default.
    //
    // Props:
    //   label -- string, required. Summary text.
    //   open -- boolean, default false. Bindable via v-model:open.
    //   streaming -- boolean, default false. Sets data-streaming and aria-busy.
    //   default slot -- reasoning content, rendered in .thinking-content.
    //   ...attrs -- fall through onto the root <details>.
    //
    // Keyboard: native <summary> (Enter / Space).
    //
    // Vue note: <details> has no two-way open binding, so the native "toggle"
    // event is mirrored into the model (the Svelte canonical uses bind:open).

    defineProps<{
        /** Summary text. */
        label: string;
        /** Whether content is still being produced. */
        streaming?: boolean;
    }>();

    const open = defineModel<boolean>("open", { default: false });

    function ontoggle(event: Event) {
        open.value = (event.target as HTMLDetailsElement).open;
    }

</script>

<template>
    <!-- Thinking.vue -->
    <details
        class="thinking"
        :open="open"
        :data-streaming="streaming ? 'true' : undefined"
        :aria-busy="streaming ? 'true' : undefined"
        @toggle="ontoggle"
    >
        <summary class="thinking-summary">{{ label }}</summary>
        <div class="thinking-content">
            <slot />
        </div>
    </details>
</template>

// lily-design-system-angular-headless/components/Thinking.ts
import { ChangeDetectionStrategy, Component, input, model } from "@angular/core";

/**
 * Thinking — a collapsible block that shows an AI agent's reasoning or thinking, closed by default
 *
 * Headless Angular component. Root native `<details class="thinking">` with
 * `<summary class="thinking-summary">{label}</summary>` and
 * `<div class="thinking-content">`. `open` is a bindable boolean (default
 * false); `streaming` sets `data-streaming` and `aria-busy` on the root.
 * Keyboard: native summary. Ships zero CSS.
 */
@Component({
  selector: "lily-thinking",
  standalone: true,
  template: `<details
    class="thinking {{ className() }}"
    [open]="open()"
    [attr.data-streaming]="streaming() ? 'true' : null"
    [attr.aria-busy]="streaming() ? 'true' : null"
    (toggle)="open.set($any($event.target).open)"
  ><summary class="thinking-summary">{{ label() }}</summary><div class="thinking-content"><ng-content /></div></details>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Thinking {
  /** The summary text. */
  readonly label = input.required<string>();
  readonly className = input<string>("");
  /** Whether the details is open. Bindable. */
  readonly open = model<boolean>(false);
  /** True while content is still arriving. */
  readonly streaming = input<boolean>(false);
}
