// lily-design-system-angular-headless/components/MultiSelectWithExtras.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  effect,
  input,
  model,
  viewChild,
} from "@angular/core";

/**
 * MultiSelectWithExtras — a multiple-choice select with additional features like search, groups, or selected-value chips
 *
 * Headless Angular component. A wrapper `<div class="multi-select-with-extras">`
 * around a native `<select multiple>` (aria-label on the select). Slots:
 * `<ng-container before>` content before the select (attribute `before`),
 * `after` content after it, and default content (options) inside it.
 * `value` is a bindable string[]. Ships zero CSS.
 *
 * Deviation from the Svelte canonical: Svelte before/after are snippets;
 * Angular uses content projection with `select="[before]"` / `select="[after]"`.
 * No rest-props spread: attributes land on the `<lily-...>` host.
 */
@Component({
  selector: "lily-multi-select-with-extras",
  standalone: true,
  template: `<div class="multi-select-with-extras {{ className() }}">
    <ng-content select="[before]" />
    <select
      #select
      multiple
      [attr.aria-label]="label()"
      [attr.size]="size() ?? null"
      [required]="required()"
      [disabled]="disabled()"
      (change)="onChange()"
    ><ng-content /></select>
    <ng-content select="[after]" />
  </div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MultiSelectWithExtras {
  /** Accessible label, applied to the select's aria-label. */
  readonly label = input.required<string>();
  readonly className = input<string>("");
  /** Bindable selected option values. */
  readonly value = model<string[]>([]);
  readonly size = input<number | undefined>(undefined);
  readonly required = input<boolean>(false);
  readonly disabled = input<boolean>(false);

  private readonly select = viewChild.required<ElementRef<HTMLSelectElement>>("select");

  constructor() {
    effect(() => {
      const selected = this.value();
      for (const option of Array.from(this.select().nativeElement.options)) {
        option.selected = selected.includes(option.value);
      }
    });
  }

  protected onChange(): void {
    this.value.set(
      Array.from(this.select().nativeElement.selectedOptions).map((o) => o.value),
    );
  }
}

// lily-design-system-react-headless/components/MultiSelectWithExtras.tsx
// MultiSelectWithExtras component
//
// A wrapper <div> with optional before/after content around a native
// <select multiple>. The accessible name sits on the select, not the wrapper.
//
// Props:
//   className -- string, optional. CSS class name (wrapper).
//   label -- string, required. aria-label on the <select>.
//   value -- string[], default []. Selected values; onChange receives the array.
//   size -- number, optional. Visible rows.
//   required, disabled -- standard form props (on the select).
//   before, after -- ReactNode, optional. Content around the select.
//   children -- Option elements.
//   ...restProps -- spread onto the wrapper <div>.
//
// Keyboard: native <select multiple>.

import React, { useEffect, useState } from "react";

export interface MultiSelectWithExtrasProps {
    className?: string;
    /** Accessible label (on the select). */
    label: string;
    /** Selected values. Bindable. */
    value?: string[];
    /** Visible rows. */
    size?: number;
    /** Whether required. */
    required?: boolean;
    /** Whether disabled. */
    disabled?: boolean;
    /** Option elements. */
    children?: React.ReactNode;
    /** Content before the select. */
    before?: React.ReactNode;
    /** Content after the select. */
    after?: React.ReactNode;
    /** Callback when the selection changes. */
    onChange?: (value: string[]) => void;
    [key: string]: unknown;
}

export default function MultiSelectWithExtras({
    className = "",
    label,
    value: valueProp = [],
    size = undefined,
    required = false,
    disabled = false,
    before,
    after,
    onChange,
    children,
    ...restProps
}: MultiSelectWithExtrasProps) {
    const [value, setValue] = useState<string[]>(valueProp);
    const key = valueProp.join("\u0000");
    useEffect(() => {
        setValue(valueProp);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [key]);

    return (
        <div className={`multi-select-with-extras ${className}`} {...restProps}>
            {before && before}
            <select
                multiple
                aria-label={label}
                size={size}
                value={value}
                onChange={(e) => {
                    const next = Array.from(e.target.selectedOptions).map((o) => o.value);
                    setValue(next);
                    onChange?.(next);
                }}
                required={required}
                disabled={disabled}
            >
                {children}
            </select>
            {after && after}
        </div>
    );
}
