// lily-design-system-angular-helpers/lily-design-system-angular-picker-bar/picker-bar.component.ts
import { ChangeDetectionStrategy, Component, input, model, output } from "@angular/core";

import {
  LinkPicker,
  type LinkItem,
  type LinkNavigatedEvent,
} from "@lilydesignsystem/angular-link-picker";
import { ThemePicker } from "@lilydesignsystem/angular-theme-picker";
import { LocalePicker } from "@lilydesignsystem/angular-locale-picker";
import { TextSizePicker } from "@lilydesignsystem/angular-text-size-picker";
import {
  SharePicker,
  type ShareEvent,
  type ShareStrategy,
  type ShareTarget,
} from "@lilydesignsystem/angular-share-picker";
import {
  SearchPicker,
  type SearchEvent,
} from "@lilydesignsystem/angular-search-picker";

/**
 * All 45 Lily reference theme slugs (see `themes/` at the repo root),
 * sorted alphabetically except the United Kingdom and United States
 * government/public-sector themes, which sort last as one alphabetical
 * group of their own. Mirrors `theme-picker`'s own title-casing of each
 * slug, so no `themeLabels` override is needed for these to read well.
 */
export const DEFAULT_THEMES: string[] = [
  "abyss",
  "acid",
  "adobe-spectrum",
  "aqua",
  "autumn",
  "black",
  "bumblebee",
  "business",
  "caramellatte",
  "cmyk",
  "coffee",
  "corporate",
  "cupcake",
  "cyberpunk",
  "dark",
  "dim",
  "dracula",
  "emerald",
  "fantasy",
  "forest",
  "garden",
  "halloween",
  "lemonade",
  "light",
  "lofi",
  "luxury",
  "mozilla-protocol",
  "night",
  "nord",
  "pastel",
  "retro",
  "silk",
  "sunset",
  "synthwave",
  "valentine",
  "winter",
  "wireframe",
  "united-kingdom-government-digital-service",
  "united-kingdom-national-health-service-england-for-patients",
  "united-kingdom-national-health-service-england-for-practitioners",
  "united-kingdom-national-health-service-scotland-for-patients",
  "united-kingdom-national-health-service-scotland-for-practitioners",
  "united-kingdom-national-health-service-wales-for-patients",
  "united-kingdom-national-health-service-wales-for-practitioners",
  "united-states-web-design-system",
];

/**
 * The seven-step text-size scale. Each slug title-cases to exactly the
 * requested label ("largest" → "Largest", …) via `text-size-picker`'s
 * own default `labelFor`, so no `sizeLabels` override is needed either.
 */
export const DEFAULT_SIZES: string[] = [
  "largest",
  "larger",
  "large",
  "normal",
  "small",
  "smaller",
  "smallest",
];

/** Accessible names for the pickers. Required — no English default (`link` only when `links` is given). */
export type PickerBarLabels = {
  /**
   * Accessible name for the link picker's button and list. Needed only when `links` is
   * supplied; the link picker renders only when both are present.
   */
  link?: string;
  /** Accessible name for the search picker's button and search landmark. */
  search: string;
  /** Accessible name for the search picker's text field. */
  searchInput: string;
  /** Accessible name for the search picker's ⏎ submit button. */
  searchSubmit: string;
  /** Accessible name for the theme picker's button and listbox. */
  theme: string;
  /** Accessible name for the locale picker's button and listbox. */
  locale: string;
  /** Accessible name for the text-size picker's button and listbox. */
  textSize: string;
  /** Accessible name for the share picker's button and list. */
  share: string;
};

/**
 * PickerBar — composes search-picker, theme-picker, locale-picker,
 * text-size-picker, and share-picker into one page-header row.
 *
 * A thin wrapper: it renders the five picker components, each imported
 * as a real npm dependency from its own published package, unmodified.
 * It pre-wires two catalog-specific defaults (`DEFAULT_THEMES`,
 * `DEFAULT_SIZES`) and flattens each wrapped picker's most commonly
 * needed optional props onto its own inputs — Angular has no spread
 * binding for component inputs, so unlike the canonical Svelte
 * contract's `*Props` bag, overrides here are named inputs rather than
 * an object spread. `motion-picker` and `date-time-picker` are
 * deliberately not included — see `spec/index.md` §1.
 */
@Component({
  selector: "lily-picker-bar",
  standalone: true,
  imports: [LinkPicker, SearchPicker, ThemePicker, LocalePicker, TextSizePicker, SharePicker],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="picker-bar {{ className() }}">
      @if (links().length > 0 && labels().link) {
        <lily-link-picker
          [label]="labels().link!"
          [links]="links()"
          [navigate]="linkNavigate()"
          (navigated)="linkNavigated.emit($event)"
        />
      }
      <lily-search-picker
        [label]="labels().search"
        [inputLabel]="labels().searchInput"
        [submitLabel]="labels().searchSubmit"
        [placeholder]="searchPlaceholder()"
        [(value)]="searchValue"
        [action]="searchAction()"
        [navigate]="searchNavigate()"
        (searched)="searched.emit($event)"
      />
      <lily-theme-picker
        [label]="labels().theme"
        [themesUrl]="themesUrl()"
        [themes]="themes()"
        [(value)]="themeValue"
        [defaultValue]="themeDefaultValue()"
        [storageKey]="themeStorageKey()"
        [detectFromSystem]="themeDetectFromSystem()"
        [name]="themeName()"
        [target]="themeTarget()"
        [themeLabels]="themeLabels()"
      />
      <lily-locale-picker
        [label]="labels().locale"
        [locales]="locales()"
        [(value)]="localeValue"
        [defaultValue]="localeDefaultValue()"
        [storageKey]="localeStorageKey()"
        [detectFromNavigator]="localeDetectFromNavigator()"
        [name]="localeName()"
        [target]="localeTarget()"
        [applyDir]="localeApplyDir()"
        [localeLabels]="localeLabels()"
      />
      <lily-text-size-picker
        [label]="labels().textSize"
        [sizes]="sizes()"
        [(value)]="textSizeValue"
        [defaultValue]="textSizeDefaultValue()"
        [storageKey]="textSizeStorageKey()"
        [name]="textSizeName()"
        [target]="textSizeTarget()"
        [sizeLabels]="textSizeLabels()"
      />
      <lily-share-picker
        [label]="labels().share"
        [targets]="shareTargets()"
        [url]="shareUrl()"
        [title]="shareTitle()"
        [text]="shareText()"
        [copyLabel]="copyLabel()"
        [copiedLabel]="copiedLabel()"
        [copyFailedLabel]="copyFailedLabel()"
        [strategy]="shareStrategy()"
        (share)="share.emit($event)"
        (copy)="copy.emit($event)"
        (nativeShare)="nativeShare.emit($event)"
      />
    </div>
  `,
})
export class PickerBar {
  /** Accessible names for each picker. */
  readonly labels = input.required<PickerBarLabels>();

  // --- link-picker ---
  /**
   * Page links for the link picker (a home icon), which renders FIRST — leftmost. Defined by the
   * app; omitted or empty means no link picker (and `labels().link` is then unused).
   */
  readonly links = input<LinkItem[]>([]);
  /** Client-side navigation hook for the links, e.g. a router's `navigateByUrl`. */
  readonly linkNavigate = input<((href: string) => void) | undefined>(undefined);
  /** Fires after a page link is chosen. */
  readonly linkNavigated = output<LinkNavigatedEvent>();

  // --- search-picker ---
  /** Placeholder for the search field. No default (it would be English). */
  readonly searchPlaceholder = input<string | undefined>(undefined);
  /** Two-way bindable search text. */
  readonly searchValue = model<string>("");
  /** Path the query is appended to (`${searchAction}?${query}`). */
  readonly searchAction = input<string>("/");
  /** Performs the search navigation. Defaults to `location.assign(href)`. */
  readonly searchNavigate = input<((href: string) => void) | undefined>(undefined);
  /** Fires with the trimmed query and destination, before navigating. */
  readonly searched = output<SearchEvent>();

  // --- theme-picker ---
  /** Base URL of the themes directory, forwarded to ThemePicker. */
  readonly themesUrl = input.required<string>();
  /** Available theme slugs. Defaults to {@link DEFAULT_THEMES}. */
  readonly themes = input<string[]>(DEFAULT_THEMES);
  /** Two-way bindable current theme slug. */
  readonly themeValue = model<string>("");
  readonly themeDefaultValue = input<string>("");
  readonly themeStorageKey = input<string>("");
  readonly themeDetectFromSystem = input<boolean>(false);
  readonly themeName = input<string>("theme");
  readonly themeTarget = input<HTMLElement | null>(null);
  readonly themeLabels = input<Record<string, string>>({});

  // --- locale-picker ---
  /** Available locale codes. No catalog default exists — supply the set you support. */
  readonly locales = input.required<string[]>();
  /** Two-way bindable current locale code. */
  readonly localeValue = model<string>("");
  readonly localeDefaultValue = input<string>("");
  readonly localeStorageKey = input<string>("");
  readonly localeDetectFromNavigator = input<boolean>(false);
  readonly localeName = input<string>("locale");
  readonly localeTarget = input<HTMLElement | null>(null);
  readonly localeApplyDir = input<boolean>(true);
  readonly localeLabels = input<Record<string, string>>({});

  // --- text-size-picker ---
  /** Available size slugs. Defaults to {@link DEFAULT_SIZES}. */
  readonly sizes = input<string[]>(DEFAULT_SIZES);
  /** Two-way bindable current size slug. */
  readonly textSizeValue = model<string>("");
  /**
   * `text-size-picker`'s own fallback ("medium", else `sizes[0]`) does
   * not fit the seven-slug scale — "medium" is not one of the seven,
   * and `sizes[0]` would silently start every consumer on "Largest".
   */
  readonly textSizeDefaultValue = input<string>("normal");
  readonly textSizeStorageKey = input<string>("");
  readonly textSizeName = input<string>("text-size");
  readonly textSizeTarget = input<HTMLElement | null>(null);
  readonly textSizeLabels = input<Record<string, string>>({});

  // --- share-picker ---
  /** Destinations offered by the share picker. Empty is valid if `copyLabel` is set. */
  readonly shareTargets = input<ShareTarget[]>([]);
  readonly shareUrl = input<string>("");
  readonly shareTitle = input<string>("");
  readonly shareText = input<string>("");
  readonly copyLabel = input<string>("");
  readonly copiedLabel = input<string>("");
  readonly copyFailedLabel = input<string>("");
  readonly shareStrategy = input<ShareStrategy>("auto");
  /** Fires after a share destination is chosen. */
  readonly share = output<ShareEvent>();
  /** Fires after the URL is copied. */
  readonly copy = output<string>();
  /** Fires when the native share sheet was used instead of the list. */
  readonly nativeShare = output<string>();

  /** Extra CSS class on the root. */
  readonly className = input<string>("");
}

// lily-design-system-vue-helpers/lily-design-system-vue-picker-bar/PickerBar.vue
<script lang="ts">
import ThemePicker from "@lilydesignsystem/vue-theme-picker";
import LocalePicker from "@lilydesignsystem/vue-locale-picker";
import TextSizePicker from "@lilydesignsystem/vue-text-size-picker";
import SharePicker from "@lilydesignsystem/vue-share-picker";
import LinkPicker from "@lilydesignsystem/vue-link-picker";
import SearchPicker from "@lilydesignsystem/vue-search-picker";
import type { Props as ThemePickerProps } from "@lilydesignsystem/vue-theme-picker";
import type { Props as LocalePickerProps } from "@lilydesignsystem/vue-locale-picker";
import type { Props as TextSizePickerProps } from "@lilydesignsystem/vue-text-size-picker";
import type {
    Props as SharePickerProps,
    ShareTarget,
} from "@lilydesignsystem/vue-share-picker";
import type { Props as SearchPickerProps } from "@lilydesignsystem/vue-search-picker";
import type {
    Props as LinkPickerProps,
    LinkItem,
} from "@lilydesignsystem/vue-link-picker";

/**
 * All 45 Lily reference theme slugs (see `themes/` at the repo root),
 * sorted alphabetically except the United Kingdom and United States
 * government/public-sector themes, which sort last as one alphabetical
 * group of their own. Mirrors `theme-picker`'s own title-casing of each
 * slug, so no `themeLabels` override is needed for these to read well.
 */
export const DEFAULT_THEMES: string[] = [
    "abyss",
    "acid",
    "adobe-spectrum",
    "aqua",
    "autumn",
    "black",
    "bumblebee",
    "business",
    "caramellatte",
    "cmyk",
    "coffee",
    "corporate",
    "cupcake",
    "cyberpunk",
    "dark",
    "dim",
    "dracula",
    "emerald",
    "fantasy",
    "forest",
    "garden",
    "halloween",
    "lemonade",
    "light",
    "lofi",
    "luxury",
    "mozilla-protocol",
    "night",
    "nord",
    "pastel",
    "retro",
    "silk",
    "sunset",
    "synthwave",
    "valentine",
    "winter",
    "wireframe",
    "united-kingdom-government-digital-service",
    "united-kingdom-national-health-service-england-for-patients",
    "united-kingdom-national-health-service-england-for-practitioners",
    "united-kingdom-national-health-service-scotland-for-patients",
    "united-kingdom-national-health-service-scotland-for-practitioners",
    "united-kingdom-national-health-service-wales-for-patients",
    "united-kingdom-national-health-service-wales-for-practitioners",
    "united-states-web-design-system",
];

/**
 * The seven-step text-size scale. Each slug title-cases to exactly the
 * requested label ("largest" → "Largest", …) via `text-size-picker`'s
 * own default `labelFor`, so no `sizeLabels` override is needed either.
 */
export const DEFAULT_SIZES: string[] = [
    "largest",
    "larger",
    "large",
    "normal",
    "small",
    "smaller",
    "smallest",
];

/** Accessible names for the pickers. Required — no English default (`link` only when `links` is given). */
export type PickerBarLabels = {
    /**
     * Accessible name for the link picker's button and list. Needed only when `links` is
     * supplied; the link picker renders only when both are present.
     */
    link?: string;
    /** Accessible name for the search picker's button and search landmark. */
    search: string;
    /** Accessible name for the search picker's text field. */
    searchInput: string;
    /** Accessible name for the search picker's ⏎ submit button. */
    searchSubmit: string;
    /** Accessible name for the theme picker's button and listbox. */
    theme: string;
    /** Accessible name for the locale picker's button and listbox. */
    locale: string;
    /** Accessible name for the text-size picker's button and listbox. */
    textSize: string;
    /** Accessible name for the share picker's button and list. */
    share: string;
};

/** Public props for PickerBar. See `spec/index.md` §4 for the contract. */
export type Props = {
    /** Accessible names for each picker. */
    labels: PickerBarLabels;

    /** Page links for the link picker (a home icon), which renders FIRST — leftmost. Omitted or empty: no link picker. */
    links?: LinkItem[];
    /** Extra LinkPicker props (e.g. `navigate`), bound after this bar's own. */
    linkProps?: Partial<Omit<LinkPickerProps, "label" | "links" | "class">>;

    /** Extra SearchPicker props (e.g. `action`, `navigate`, `placeholder`), bound after this bar's own. */
    searchProps?: Partial<
        Omit<SearchPickerProps, "label" | "inputLabel" | "submitLabel" | "class">
    >;

    /** Base URL of the themes directory, forwarded to ThemePicker. */
    themesUrl: string;
    /** Available theme slugs. Defaults to {@link DEFAULT_THEMES}. */
    themes?: string[];
    /** Extra ThemePicker props, bound after this bar's own (v-bind="themeProps"). */
    themeProps?: Partial<
        Omit<ThemePickerProps, "label" | "themesUrl" | "themes" | "class">
    >;

    /** Available locale codes. No catalog default exists — supply the set you support. */
    locales: string[];
    /** Extra LocalePicker props, bound after this bar's own. */
    localeProps?: Partial<Omit<LocalePickerProps, "label" | "locales" | "class">>;

    /** Available size slugs. Defaults to {@link DEFAULT_SIZES}. */
    sizes?: string[];
    /** Extra TextSizePicker props, bound after this bar's own. */
    textSizeProps?: Partial<
        Omit<TextSizePickerProps, "label" | "sizes" | "class">
    >;

    /** Destinations offered by the share picker. Empty is valid if `shareProps.copyLabel` is set. */
    shareTargets?: ShareTarget[];
    /** Extra SharePicker props, bound after this bar's own. */
    shareProps?: Partial<Omit<SharePickerProps, "label" | "targets" | "class">>;

    /** Extra CSS class on the root element. */
    class?: string;
};
</script>

<script setup lang="ts">
const props = withDefaults(defineProps<Props>(), {
    links: () => [],
    linkProps: () => ({}),
    searchProps: () => ({}),
    themes: () => DEFAULT_THEMES,
    themeProps: () => ({}),
    localeProps: () => ({}),
    sizes: () => DEFAULT_SIZES,
    textSizeProps: () => ({}),
    shareTargets: () => [],
    shareProps: () => ({}),
    class: "",
});

// Vue separates props from events by design, so — unlike the Svelte
// canonical's `onChange` prop inside each `*Props` bag — the Vue port
// re-emits each wrapped picker's own event under a bar-scoped name,
// fully typed, rather than accepting an untyped `onChange` key inside
// `themeProps` et al.
const emit = defineEmits<{
    (event: "link-navigate", id: string, href: string): void;
    (event: "search", query: string, href: string): void;
    (event: "theme-change", value: string): void;
    (event: "locale-change", value: string): void;
    (event: "text-size-change", value: string): void;
    (event: "share", targetId: string, url: string): void;
    (event: "copy", url: string): void;
    (event: "native-share", url: string): void;
}>();
</script>

<template>
    <div :class="`picker-bar ${props.class}`.trim()">
        <LinkPicker
            v-if="links.length > 0 && labels.link"
            :label="labels.link"
            :links="links"
            v-bind="linkProps"
            @navigate="(id: string, href: string) => emit('link-navigate', id, href)"
        />
        <SearchPicker
            :label="labels.search"
            :inputLabel="labels.searchInput"
            :submitLabel="labels.searchSubmit"
            v-bind="searchProps"
            @search="(query: string, href: string) => emit('search', query, href)"
        />
        <ThemePicker
            :label="labels.theme"
            :themesUrl="themesUrl"
            :themes="themes"
            v-bind="themeProps"
            @change="(value: string) => emit('theme-change', value)"
        />
        <LocalePicker
            :label="labels.locale"
            :locales="locales"
            v-bind="localeProps"
            @change="(value: string) => emit('locale-change', value)"
        />
        <TextSizePicker
            :label="labels.textSize"
            :sizes="sizes"
            defaultValue="normal"
            v-bind="textSizeProps"
            @change="(value: string) => emit('text-size-change', value)"
        />
        <SharePicker
            :label="labels.share"
            :targets="shareTargets"
            v-bind="shareProps"
            @share="(targetId: string, url: string) => emit('share', targetId, url)"
            @copy="(url: string) => emit('copy', url)"
            @nativeShare="(url: string) => emit('native-share', url)"
        />
    </div>
</template>
